from setuptools import setup, find_packages

setup(
    name="claims-engine",
    version="0.1.0",
    description="Intelligent Claims Triage & Fraud Risk Engine",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(),
    python_requires=">=3.11",
    install_requires=[
        "fastapi==0.109.0",
        "uvicorn==0.27.0",
        "pydantic==2.6.0",
        "torch==2.2.0",
        "transformers==4.37.0",
        "scikit-learn==1.4.1",
        "xgboost==2.0.3",
        "spacy==3.7.2",
        "sqlalchemy==2.0.25",
        "psycopg2-binary==2.9.9",
        "redis==5.0.1",
        "kafka-python==2.0.2",
        "aio-pika==13.0.1",
        "streamlit==1.31.0",
        "groq==0.7.0",
        "openai==1.3.0",
        "langchain>=0.3.0,<1.0",
        "langchain-community>=0.3.0,<1.0",
        "langchain-openai>=0.1.0",
        "faiss-cpu>=1.8.0",
        "pytest==7.4.4",
        "pytest-cov==4.1.0",
        "black==24.1.1",
        "flake8==7.0.0",
        "mypy==1.8.0",
        "python-dotenv==1.0.0",
        "python-logging-loki==0.3.2",
    ],
)
