from setuptools import setup, find_packages

setup(
    name="claims-engine",
    version="0.1.0",
    description="Intelligent Claims Triage & Fraud Risk Engine",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(),
    python_requires=">=3.11",
    install_requires=[
        "fastapi>=0.104.0",
        "uvicorn>=0.24.0",
        "pydantic>=2.5.0",
        "torch>=2.1.0",
        "transformers>=4.35.0",
        "scikit-learn>=1.4.0",
        "xgboost>=2.0.0",
        "spacy>=3.7.0",
        "sqlalchemy>=2.0.20",
        "psycopg2-binary>=2.9.9",
        "redis>=5.0.0",
        "kafka-python>=2.0.0",
        "aio-pika>=9.6.0",
        "streamlit>=1.30.0",
        "groq>=0.6.0",
        "openai>=1.3.0",
        "langchain>=0.3.0",
        "langchain-community>=0.3.0",
        "langchain-openai>=0.1.0",
        "faiss-cpu>=1.8.0",
        "pytest>=7.4.0",
        "pytest-cov>=4.1.0",
        "black>=24.1.0",
        "flake8>=7.0.0",
        "mypy>=1.8.0",
        "python-dotenv>=1.0.0",
        "python-logging-loki>=0.3.0",
    ],
)
